### ISSUE TITLE
Fail  need more than 0 values to unpack

### ISSUE THREAD

**Issue by Azd325** [NativeInstruments/puck#5]
If in the requirements.txt some comment it will fail.

```
# some comment
django==1.11
```

**Comment by stchris** [comment]
Ah, nice catch. I'll add a test and see how to fix it. Thanks for reporting this!

**Comment by stchris** [comment]
@Azd325 I've released `1.0.5` with a fix for this. Can you try it?

**Comment by Azd325** [comment]
It works.
