### ISSUE TITLE
puck can't be installed when using Python 3

### ISSUE THREAD

**Issue by svisser** [NativeInstruments/puck#8]
The wheel file on PyPI is marked as Python 2.x only so it's currently not possible to install the project when using Python 3:

```bash
$ python3 -m pip install puck
Collecting puck
  Could not find a version that satisfies the requirement puck (from versions: )
No matching distribution found for puck
```

**Comment by stchris** [comment]
This works with `1.0.6`, now available on Pypi :) 

Thanks for reporting this <3

**Comment by svisser** [comment]
Thanks for this as well!
